#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=isharah_exp_debug
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=00:30:00
#SBATCH --output=jobs/output/slurm_isharah_exp_debug_%A.txt

module purge
module load 2025

cd $HOME/Fork_SlowFastSign
source .venv/bin/activate

srun python main.py --config configs/isharah_exp1.yaml --device 0 --dataset Isharah --num-epoch 1 --eval-interval 1 --num-worker 4 --feeder-args max_samples=50 --work-dir ./work_dir/isharah_exp_debug/ --mlflow-experiment SlowFastSign-Isharah
