#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=isharah_train
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=24:00:00
#SBATCH --output=jobs/output/slurm_isharah_train_%A.txt

module purge
module load 2025

cd $HOME/Fork_SlowFastSign
source .venv/bin/activate

srun python main.py --device 0 --dataset Isharah --num-epoch 80 --work-dir ./work_dir/isharah/ --mlflow-experiment SlowFastSign-Isharah
