#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=isharah_exp2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=24:00:00
#SBATCH --output=/scratch-shared/psobecki/Fork_SlowFastSign/jobs/output/slurm_isharah_exp2_%A.txt

module purge
module load 2025

cd $HOME/Fork_SlowFastSign
source .venv/bin/activate

srun python main.py --config configs/isharah_exp2.yaml --device 0 --dataset Isharah --num-epoch 80 --work-dir /scratch-shared/psobecki/Fork_SlowFastSign/work_dir/isharah_exp2/ --mlflow-experiment SlowFastSign-Isharah
